/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package aux2;

import java.awt.*;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.geom.Rectangle2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import mazeagram.Interface;

/**
 *
 * @author SONY
 */
public class PanelSalida extends javax.swing.JPanel 
                         implements Runnable,
                         MouseListener{

    /**
     * Creates new form PanelSalida
     */
    private BufferedImage bufferImagen,
                          bufferLogo,
                          bufferTextura;
    private TexturePaint patronGeneral;
    private Interface ventanaJuego;
    private int inicioLetras=640;
    private boolean banderaSalida=true;
    private  Font fuente;
    private Rectangle2D botonM,
                        botonS;
    
    public PanelSalida(Interface ventanaJuego){
        this.ventanaJuego=ventanaJuego;
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension dv = tk.getScreenSize();
        Cursor c;
        ImageIcon image = new ImageIcon("Imagenes/puntero.png");
        c = tk.createCustomCursor(image.getImage(), new Point(0,0), "cursorName");
        setCursor(c);
        
        try {
            bufferImagen= ImageIO.read(new File("./Textures/panel.PNG"));
            bufferLogo= ImageIO.read(new File("./Textures/Logo.PNG"));
            bufferTextura= ImageIO.read(new File("./Textures/texturaFinal.BMP"));
            Rectangle2D reC=new Rectangle2D.Double(0,0,bufferTextura.getWidth(),bufferTextura.getHeight());
            patronGeneral=new TexturePaint(bufferTextura, reC);
            fuente = Font.createFont(Font.TRUETYPE_FONT,new File("./Fuentes/2.ttf"));
            fuente = fuente.deriveFont(60.5f);
            botonM=new Rectangle2D.Float(50,700, 150, 50);
            botonS=new Rectangle2D.Float(1100,700, 150, 50);
            addMouseListener(this);
        } catch (IOException ex) {
            Logger.getLogger(PanelSalida.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (FontFormatException ex) {
            Logger.getLogger(PanelSalida.class.getName()).log(Level.SEVERE, null, ex);
        }
         new Thread(this).start();
    }

    @Override
    public void paint(Graphics g) {
//        super.paint(g);
        Graphics2D g2d=(Graphics2D)g;
        Image mImagen   =createImage(getWidth(),getHeight());
        try{
        Graphics2D offG =(Graphics2D) mImagen.getGraphics();
         offG.setPaint(patronGeneral);
         offG.fillRect(0,0, 
                getWidth(),getHeight()-100);
        offG.setColor(Color.WHITE);
        offG.setFont(fuente);
        offG.setColor(new Color(255,216,0));
        offG.drawString("Creditos", 100, inicioLetras);
        offG.drawString("MAZEGRAM", 100, inicioLetras+100);
        offG.drawString("TEAM DEVELOPER", 100, inicioLetras+200);
        offG.setColor(new Color(174,217,231));
        offG.drawString("Hector Morales Palma", 100, inicioLetras+250);
        offG.drawString("Jesus Guzman Mondragon", 100, inicioLetras+300);
        offG.drawString("Sandra Marlen Gutierrez Pineda", 100, inicioLetras+350);
        offG.setColor(new Color(255,216,0));
        offG.drawString("Sonidos/Graficos", 100, inicioLetras+450);
        offG.setColor(new Color(174,217,231));
        offG.drawString("www.openart.com  HorrorPen", 100, inicioLetras+500);
        offG.setColor(new Color(255,216,0));
        offG.drawString("2012", 100, inicioLetras+600);
        offG.drawString("MAZEGRAM", 100, inicioLetras+800);
        offG.setColor(Color.BLACK);
        offG.fillRect(0,getHeight()-100, 
                getWidth(),100);
        offG.setColor(Color.red);
        offG.fill(botonM);
        offG.fill(botonS);
        offG.setColor(Color.WHITE);
        offG.drawString("Menu",60,745);
        offG.drawString("Salir",1110,745);
        g2d.drawImage(mImagen, 0,0,this);
        
        }catch(Exception e){
                
                }
    }
    public void repintar(){
        paint(getGraphics());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while(inicioLetras>=-600 && banderaSalida){
            inicioLetras-=1;
            try {
                Thread.sleep(10);
                repintar();
            } catch (InterruptedException ex) {
                System.out.println("etnro");
            }
           
       }
    }

    @Override
    public void mouseClicked(MouseEvent e) {}
    @Override
    public void mousePressed(MouseEvent e) {
        if(botonM.contains(e.getPoint())){
            banderaSalida=false;
            ventanaJuego.establecerMenu();
        }else if(botonS.contains(e.getPoint())){
            System.exit(0);
        }
    }
    @Override
    public void mouseReleased(MouseEvent e) {}
    @Override
    public void mouseEntered(MouseEvent e) {}
    @Override
    public void mouseExited(MouseEvent e) {}
}
